# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path pathlist to be added to the python path
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to allow for slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded
# when using prepend_sys_path
# rm_dependency_check = false

# logging configuration URL (default is logg_file)
# config_file =

# sqlalchemy.url = postgresql://healthadmin:healthpassword@db:5432/healthvault


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
